[package]
name = "rust-server-actix"
version = "0.1.0"
authors = ["peter.mares"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "1.0"
