[package]
name = "rust-server-warp"
version = "0.1.0"
authors = ["peter.mares"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.13", features = ["macros"] }
warp = "0.2"